# Image running node 14, the runtime version Azure Function uses for TypeScript
# https://docs.microsoft.com/en-us/azure/azure-functions/functions-versions
image: node:14

# This folder is cached between builds
# https://docs.gitlab.com/ee/ci/yaml/index.html#cache
cache:
  paths:
    - node_modules/

include:
  - project: 'prodsec/whitesource'
    ref: latest
    file: '/templates/.whitesource.yml'

whitesource:
  extends: .whitesource
  stage: test
  variables:
    ws_user_key: ${WHITESOURCE_USER_KEY}
    product_id: ${WHITESOURCE_ID}
    config: js-npm
  only:
    refs:
      - main

test:
  script:
    - npm install
    - npm run build
    - npm test
